# Generated by Django 5.1.1 on 2024-09-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digimon', '0002_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='digimon',
            name='moves',
            field=models.ManyToManyField(to='digimon.move'),
        ),
    ]
