# Generated by Django 5.1.1 on 2024-09-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digimon', '0004_digimon_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digicrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('digimon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digimon.digimon')),
            ],
        ),
    ]
